name=input("enter your name:")
reg_no=int(input("enter your register number:"))
clg_name=input("enter your college name:")
department=input("enter your department:")
print("output")
print("name:",name)
print("register number:",reg_no)
print("college name:",clg_name)
print("department:",department)